In [10]:
import pandas as pd
path = r'C:\Users\HMLAP01\Documents\hotel_bookings.csv'
hotel_bookings = pd.read_csv(path)

In [11]:
hotel_bookings

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [9]:
df.rename({'adults' : 'num_adults', 'children': 'num_children', 'babies' : 'num_babies'}, axis=1, inplace=True)
df.head(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,num_adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03
7,Resort Hotel,0,9,2015,July,27,1,0,2,2,...,No Deposit,303.0,NaN,0,Transient,103.0,0,1,Check-Out,2015-07-03
8,Resort Hotel,1,85,2015,July,27,1,0,3,2,...,No Deposit,240.0,NaN,0,Transient,82.0,0,1,Canceled,2015-05-06
9,Resort Hotel,1,75,2015,July,27,1,0,3,2,...,No Deposit,15.0,NaN,0,Transient,105.5,0,0,Canceled,2015-04-22

In [42]:
hotel_bookings.isnull().sum()*100/len(hotel_bookings)

hotel                             0.0
is_canceled                       0.0
lead_time                         0.0
arrival_date_year                 0.0
arrival_date_month                0.0
arrival_date_week_number          0.0
arrival_date_day_of_month         0.0
stays_in_weekend_nights           0.0
stays_in_week_nights              0.0
adults                            0.0
children                          0.0
babies                            0.0
meal                              0.0
country                           0.0
market_segment                    0.0
distribution_channel              0.0
is_repeated_guest                 0.0
previous_cancellations            0.0
previous_bookings_not_canceled    0.0
reserved_room_type                0.0
assigned_room_type                0.0
booking_changes                   0.0
deposit_type                      0.0
agent                             0.0
days_in_waiting_list              0.0
customer_type                     0.0
adr                               0.0
required_car_parking_spaces       0.0
total_of_special_requests         0.0
reservation_status                0.0
reservation_status_date           0.0
dtype: float64

In [13]:
hotel_bookings['agent'].unique()
hotel_bookings[hotel_bookings['agent'] == 5]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
25,Resort Hotel,0,78,2015,July,27,1,2,5,2,...,No Deposit,5.0,NaN,0,Transient,63.60,1,0,Check-Out,2015-07-08
79,Resort Hotel,0,81,2015,July,27,3,2,6,3,...,No Deposit,5.0,NaN,0,Transient,85.86,0,0,Check-Out,2015-07-11
155,Resort Hotel,0,82,2015,July,28,5,4,6,2,...,No Deposit,5.0,NaN,0,Transient,63.60,1,2,Check-Out,2015-07-15
272,Resort Hotel,0,87,2015,July,28,10,2,5,2,...,No Deposit,5.0,NaN,0,Transient,133.83,0,2,Check-Out,2015-07-17
300,Resort Hotel,0,36,2015,July,28,11,2,5,2,...,No Deposit,5.0,NaN,0,Transient,104.68,1,0,Check-Out,2015-07-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75021,City Hotel,1,268,2015,July,29,12,2,1,2,...,No Deposit,5.0,NaN,0,Transient,82.00,0,0,Canceled,2015-06-26
75022,City Hotel,1,268,2015,July,29,12,2,1,2,...,No Deposit,5.0,NaN,0,Transient,82.00,0,0,Canceled,2015-06-26
75023,City Hotel,1,268,2015,July,29,12,2,1,2,...,No Deposit,5.0,NaN,0,Transient,82.00,0,0,Canceled,2015-06-26
75024,City Hotel,1,268,2015,July,29,12,2,1,2,...,No Deposit,5.0,NaN,0,Transient,82.00,0,0,Canceled,2015-06-26
75025,City Hotel,1,268,2015,July,29,12,2,1,2,...,No Deposit,5.0,NaN,0,Transient,82.00,0,0,Canceled,2015-06-26

In [41]:
hotel_bookings['agent'].unique()
hotel_bookings[hotel_bookings['agent'] == 5]
hotel_bookings.fillna({'agent': -1}, inplace=True)
hotel_bookings[hotel_bookings['children'].isna()]
hotel_bookings[hotel_bookings['country'].isna()][['hotel', 'is_canceled', 'country']]
hotel_bookings.fillna({'country': 'unknown'}, inplace=True)
hotel_bookings.dropna(subset=['children'], inplace=True)
hotel_bookings.drop(columns=['company'], errors='ignore', inplace=True)

In [43]:
hotel_bookings.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

In [46]:
hotel_bookings = hotel_bookings.astype({'is_canceled' : 'boolean', 'hotel' : 'object', 'is_repeated_guest' : 'boolean', 'children' : 'int', 'agent' : 'int'})
hotel_bookings.dtypes

hotel                              object
is_canceled                       boolean
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                            int64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                 boolean
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                               int64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

In [50]:
hotel_bookings['lead_time'].unique()
hotel_bookings['lead_time'].describe()
bins = [0, 100, 200, 300, 400, 500, 600, 700, 800]
labels = ['0-100', '101-200', '201-300','301-400', '401-500', '501-600', '601-700', '701-800']
hotel_bookings['lead_time_binned'] = pd.cut(hotel_bookings['lead_time'], bins=bins, labels=labels)
hotel_bookings[['lead_time', 'lead_time_binned']]

        lead_time lead_time_binned
0             342          301-400
1             737          701-800
2               7            0-100
3              13            0-100
4              14            0-100
...           ...              ...
119385         23            0-100
119386        102          101-200
119387         34            0-100
119388        109          101-200
119389        205          201-300

[119386 rows x 2 columns]

In [51]:
hotel_bookings.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,lead_time_binned
0,Resort Hotel,False,342,2015,July,27,1,0,0,2,...,No Deposit,-1,0,Transient,0.0,0,0,Check-Out,2015-07-01,301-400
1,Resort Hotel,False,737,2015,July,27,1,0,0,2,...,No Deposit,-1,0,Transient,0.0,0,0,Check-Out,2015-07-01,701-800
2,Resort Hotel,False,7,2015,July,27,1,0,1,1,...,No Deposit,-1,0,Transient,75.0,0,0,Check-Out,2015-07-02,0-100
3,Resort Hotel,False,13,2015,July,27,1,0,1,1,...,No Deposit,304,0,Transient,75.0,0,0,Check-Out,2015-07-02,0-100
4,Resort Hotel,False,14,2015,July,27,1,0,2,2,...,No Deposit,240,0,Transient,98.0,0,1,Check-Out,2015-07-03,0-100

In [52]:
hotel_bookings['hotel'].unique()

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [57]:
hotel_bookings.loc[hotel_bookings.duplicated(keep=False)]
hotel_bookings.drop_duplicates(keep="first", inplace=True)

In [58]:
hotel_bookings.loc[hotel_bookings.duplicated(keep=False)]

Empty DataFrame
Columns: [hotel, is_canceled, lead_time, arrival_date_year, arrival_date_month, arrival_date_week_number, arrival_date_day_of_month, stays_in_weekend_nights, stays_in_week_nights, adults, children, babies, meal, country, market_segment, distribution_channel, is_repeated_guest, previous_cancellations, previous_bookings_not_canceled, reserved_room_type, assigned_room_type, booking_changes, deposit_type, agent, days_in_waiting_list, customer_type, adr, required_car_parking_spaces, total_of_special_requests, reservation_status, reservation_status_date, lead_time_binned]
Index: []

[0 rows x 32 columns]